cloud_backend: s3
date_range:
  end: None
  start: None
location_name: Yellowstone National Park, US, WY
n_clusters: 5
per_page: 20
run_mode:
- llm_summary
- clustering
s3_bucket: wildlife-logs
taxon_name: null
